INSERT INTO pixelmanga.attributes (id, name, type_id, description) VALUES (1, 'manga', 1, null);
INSERT INTO pixelmanga.attributes (id, name, type_id, description) VALUES (2, 'manhwa', 1, null);
INSERT INTO pixelmanga.attributes (id, name, type_id, description) VALUES (3, 'manhua', 1, null);
INSERT INTO pixelmanga.attributes (id, name, type_id, description) VALUES (4, 'novela', 1, null);
INSERT INTO pixelmanga.attributes (id, name, type_id, description) VALUES (5, 'shounen', 3, 'Dirigido al público masculino joven');
INSERT INTO pixelmanga.attributes (id, name, type_id, description) VALUES (6, 'shoujo', 3, 'Dirigido al público femenino joven');
INSERT INTO pixelmanga.attributes (id, name, type_id, description) VALUES (7, 'seinen', 3, 'Dirigido al público masculino joven y adulto');
INSERT INTO pixelmanga.attributes (id, name, type_id, description) VALUES (8, 'josei', 3, 'Dirigido al público femenino joven y adulto');
INSERT INTO pixelmanga.attributes (id, name, type_id, description) VALUES (9, 'acción', 2, null);
INSERT INTO pixelmanga.attributes (id, name, type_id, description) VALUES (10, 'apocalíptico', 2, null);
INSERT INTO pixelmanga.attributes (id, name, type_id, description) VALUES (11, 'comedia', 2, null);
INSERT INTO pixelmanga.attributes (id, name, type_id, description) VALUES (12, 'drama', 2, null);
INSERT INTO pixelmanga.attributes (id, name, type_id, description) VALUES (13, 'recuentos de la vida', 2, null);
INSERT INTO pixelmanga.attributes (id, name, type_id, description) VALUES (14, 'fantasía', 2, null);
INSERT INTO pixelmanga.attributes (id, name, type_id, description) VALUES (15, 'ecchi', 2, null);
INSERT INTO pixelmanga.attributes (id, name, type_id, description) VALUES (16, 'magia', 2, null);
INSERT INTO pixelmanga.attributes (id, name, type_id, description) VALUES (17, 'ciencia ficción', 2, null);
INSERT INTO pixelmanga.attributes (id, name, type_id, description) VALUES (18, 'sobrenatural', 2, null);
INSERT INTO pixelmanga.attributes (id, name, type_id, description) VALUES (19, 'horror', 2, null);
INSERT INTO pixelmanga.attributes (id, name, type_id, description) VALUES (20, 'deporte', 2, null);
INSERT INTO pixelmanga.attributes (id, name, type_id, description) VALUES (21, 'yaoi', 2, null);
INSERT INTO pixelmanga.attributes (id, name, type_id, description) VALUES (22, 'yuri', 2, null);
INSERT INTO pixelmanga.attributes (id, name, type_id, description) VALUES (23, 'harem', 2, null);
INSERT INTO pixelmanga.attributes (id, name, type_id, description) VALUES (24, 'mecha', 2, null);
INSERT INTO pixelmanga.attributes (id, name, type_id, description) VALUES (25, 'supervivencia', 2, null);
INSERT INTO pixelmanga.attributes (id, name, type_id, description) VALUES (26, 'reencarnación', 2, null);
INSERT INTO pixelmanga.attributes (id, name, type_id, description) VALUES (27, 'isekai', 2, null);
INSERT INTO pixelmanga.attributes (id, name, type_id, description) VALUES (28, 'gore', 2, null);
INSERT INTO pixelmanga.attributes (id, name, type_id, description) VALUES (29, 'superpoderes', 2, null);
INSERT INTO pixelmanga.attributes (id, name, type_id, description) VALUES (30, 'artes marciales', 2, null);
INSERT INTO pixelmanga.attributes (id, name, type_id, description) VALUES (31, 'tragedia', 2, null);
INSERT INTO pixelmanga.attributes (id, name, type_id, description) VALUES (32, 'militar', 2, null);
INSERT INTO pixelmanga.attributes (id, name, type_id, description) VALUES (33, 'crimen', 2, null);
INSERT INTO pixelmanga.attributes (id, name, type_id, description) VALUES (34, 'vampiros', 2, null);
INSERT INTO pixelmanga.attributes (id, name, type_id, description) VALUES (35, 'samurái', 2, null);
INSERT INTO pixelmanga.attributes (id, name, type_id, description) VALUES (36, 'cambio de género', 2, null);
INSERT INTO pixelmanga.attributes (id, name, type_id, description) VALUES (37, 'realidad virtual', 2, null);
INSERT INTO pixelmanga.attributes (id, name, type_id, description) VALUES (38, 'ciberpunk', 2, null);
INSERT INTO pixelmanga.attributes (id, name, type_id, description) VALUES (39, 'música', 2, null);
INSERT INTO pixelmanga.attributes (id, name, type_id, description) VALUES (40, 'parodia', 2, null);
INSERT INTO pixelmanga.attributes (id, name, type_id, description) VALUES (41, 'demonios', 2, null);
INSERT INTO pixelmanga.attributes (id, name, type_id, description) VALUES (42, 'familia', 2, null);
INSERT INTO pixelmanga.attributes (id, name, type_id, description) VALUES (43, 'extranjero', 2, null);
INSERT INTO pixelmanga.attributes (id, name, type_id, description) VALUES (44, 'niños', 2, null);
INSERT INTO pixelmanga.attributes (id, name, type_id, description) VALUES (45, 'guerra', 2, null);
INSERT INTO pixelmanga.attributes (id, name, type_id, description) VALUES (46, 'historia', 2, null);
INSERT INTO pixelmanga.attributes (id, name, type_id, description) VALUES (47, 'misterio', 2, null);
INSERT INTO pixelmanga.attributes (id, name, type_id, description) VALUES (48, 'policiaca', 2, null);
INSERT INTO pixelmanga.attributes (id, name, type_id, description) VALUES (49, 'psicológico', 2, null);
INSERT INTO pixelmanga.attributes (id, name, type_id, description) VALUES (50, 'romance', 2, null);
INSERT INTO pixelmanga.attributes (id, name, type_id, description) VALUES (51, 'suspenso', 2, null);
INSERT INTO pixelmanga.attributes (id, name, type_id, description) VALUES (52, 'thriller', 2, null);
INSERT INTO pixelmanga.attributes (id, name, type_id, description) VALUES (53, 'vida escolar', 2, null);
INSERT INTO pixelmanga.attributes (id, name, type_id, description) VALUES (54, 'vida real', 2, null);
INSERT INTO pixelmanga.attributes (id, name, type_id, description) VALUES (55, 'aventura', 2, null);